# syntax=docker/dockerfile:1.4

FROM --platform=$BUILDPLATFORM ghcr.io/linkerd/dev:v47-rust-musl as cni-repair-controller
WORKDIR /build
COPY --link justfile justfile-rust .
COPY --link Cargo.toml Cargo.lock .
COPY --link validator validator
COPY --link cni-repair-controller cni-repair-controller
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    cargo fetch
RUN apt-get update
RUN apt-get install -y binutils-aarch64-linux-gnu
env CARGO="cargo auditable"
ARG TARGETARCH
# Enable tokio runtime metrics
ENV RUSTFLAGS="--cfg tokio_unstable"
ENV AWS_LC_SYS_CFLAGS="-fuse-ld=/usr/aarch64-linux-gnu/bin/ld"
RUN --mount=type=cache,target=target \
    --mount=type=cache,target=/usr/local/cargo/registry \
    target="aarch64-unknown-linux-musl" && \
    just cni-repair-controller arch="$TARGETARCH" profile=release build && \
    mv "target/$target/release/linkerd-cni-repair-controller" .

FROM --platform=$TARGETPLATFORM alpine:3.22.1 as runtime
WORKDIR /linkerd
RUN apk add \
    # For inotifywait
    inotify-tools \
    # For pgrep
    procps \
    bash \
    jq

COPY --from=cni-repair-controller /build/linkerd-cni-repair-controller /usr/lib/linkerd/
COPY LICENSE .
COPY cni-plugin/deployment/scripts/install-cni.sh .
COPY cni-plugin/deployment/scripts/filter.jq .
ENV PATH=/linkerd:/opt/cni/bin:$PATH
CMD ["install-cni.sh"]
