name: Actions

on: workflow_dispatch


permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: linkerd/dev/actions/setup-tools@v42
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - run: just action-lint

  devcontainer-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: linkerd/dev/actions/setup-tools@v42
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - run: just action-dev-check
