name: cni-plugin-integration

on:
  push: {}

jobs:
  cni-flannel-test:
    continue-on-error: true
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: linkerd/dev/actions/setup-tools@v43
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Run CNI integration tests
        run: just cni-plugin-test-integration-flannel
