name: Integration tests

on:
  push: {}

jobs:
  proxy-init-integration:
    continue-on-error: true
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: linkerd/dev/actions/setup-tools@v43
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Run proxy-init integration tests
        run: just proxy-init-test-integration
