name: reinitialize-pods release

on:
  pull_request:
    paths:
      - .github/workflows/release-reinitialize-pods.yml
  push:
    tags: ["reinitialize-pods/v*"]

permissions:
  contents: read

jobs:
  meta:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v42-rust
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: ./.github/actions/version-mode
        id: meta
        with:
          package: reinitialize-pods
          check: true
    outputs:
      repo: ${{ steps.meta.outputs.repo }}
      mode: ${{ steps.meta.outputs.mode }}
      version: ${{ steps.meta.outputs.version }}

  package:
    needs: meta
    strategy:
      matrix:
        arch: [amd64, arm64, arm]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v42-rust-musl
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - run: just reinitialize-pods arch=${{ matrix.arch }} profile=release version=${{ needs.meta.outputs.version }} package
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}-artifacts
          path: target/package/

  publish:
    needs: [meta, package]
    timeout-minutes: 5
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          path: ${{ runner.temp }}/artifacts
      - run: find "$RUNNER_TEMP"/artifacts -type f -ls
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - if: needs.meta.outputs.mode == 'release'
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          name: reinitialize-pods ${{ needs.meta.outputs.version }}
          files: ${{ runner.temp }}/artifacts/**/*

