name: cni-plugin release

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  docker-publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 25
    permissions:
      id-token: write # needed for signing the images with GitHub OIDC token
    steps:
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      - uses: linkerd/dev/actions/setup-tools@v47
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          push: false
          platforms: linux/arm64
          file: Dockerfile-cni-plugin
          tags: ghcr.io/alpeb/release-cni-plugin:test
          outputs: type=oci,dest=/tmp/release-cni-plugin:test.tar
