name: Shell

permissions:
  contents: read

on: workflow_dispatch

jobs:
  sh-lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: linkerd/dev/actions/setup-tools@v42
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - run: just sh-lint
